### ISSUE TITLE
Vertical-align and margin are not nice.

### ISSUE THREAD

**Issue by trmdi** [lipido/kargos#1]
It's like the "Vertical-align" isn't aligned to the middle, and the left/right margin is a little too far. See the screenshot below:

![screenshot](http://i.imgur.com/SJSMxRp.png)

The .sh file:
```bash
#!/bin/bash
echo "en | font=HackBold size=13"
```

**Comment by lipido** [comment]
I think Vertical-align it is now fixed in github. Could you try? To test:

```
git clone git@github.com:lipido/kargos.git
cd kargos

plasmapkg2 --remove org.kde.kargos
plasmapkg2 -t plasmoid --install .plasmoid
killall plasmashell; kstart5 plasmashell
```

**Comment by trmdi** [comment]
Ok, it is vertically aligned. Looks much better now.
About the left/right margin, after checked again, I think that space is the margin of others widget.

**I have some other suggestions:**

1. Which effect do you think better when the mouse hovers over the button? I think the one of the Share widget. (The run button is not as nice as the Share widget with the border when mouse hovers over. I mean you just need to add the border, no need to display the run button)
2. I also think it would be better if you let the user change the text when the mouse hovers over the button. (the text "kargos" and "Argos port to KDE Plasma")
![1](http://i.imgur.com/XuDwnGR.png)
![2](http://i.imgur.com/yDz0gVN.png)
3. What about an option for "preferred height" ?
![3](http://i.imgur.com/SYwgl1P.png)
4. What do you think about a new name for kargos? Don't need to keep the old name "argos". It doesn't suggest anything to one who has never used it before like me. What about "Fluid"? :D

**Comment by lipido** [comment]
Hi, awesome review!

1. The _Run_ button appears only on items which have `bash` attribute. A _Go_ button also appears on items with `href` attribute. The aspect is a standard button, nothing else. I've used buttons because you can have `href` and `bash` in the same item, so a click over the item is ambiguous, so I've used two buttons.

2. The tooltip is not a tooltip of the Run button, is a tooltip of the entire plasmoid. In any case, I think that a static text like is is currently implemented or a configuration option to place just another static text is not very useful. What about this idea? Place contents taken from the command execution to create **useful and dynamic** tooltips. For example, creating a non BitBar standard attribute like `tooltipmain` and `tooltipsub`. An example code:
```bash
#!/bin/bash

echo "en" # text on the panel
echo "Cool kargo plugin | tooltipmain=true"
echo "This kargo plugin shows the new tooltip feature $(date) | tooltipsub=true"
```

3. Implemented, just committed. :-)

4. The name... I didn't know argos nor bibar, but I saw a post in the las few days and I thought that it was so awesome that I was forced to learn to program plasmoids and take it into my beloved KDE :-). The name is a tribute to those apps.

**Comment by alxlg** [comment]
@trmdi I think the hover effect should be the one of the other plasmoids (like sys tray). The effect of share button is a bug and if I remember correctly is fixed in git.

**Comment by alxlg** [comment]
@lipido `git clone git@github.com:lipido/kargos.git` gives me error about denied permission. `git clone https://github.com/lipido/kargos.git` works instead.

**Comment by trmdi** [comment]
@lipido 
1. Could you give an option to display Run/Go button or display just a hover effect like the Share button, or even no effect at all.
2. It would be more flexible if the tooltip could be changed, for example users could hover over the time icon to see the date, no need to click to display the submenu, it is similar to the default Time date widget.

**Comment by lipido** [comment]
@trmdi
Could you please open different issues with those ideas to keep this more organized?

**Comment by trmdi** [comment]
Ok, I did that. Please go to https://github.com/lipido/kargos/issues/2
