### ISSUE TITLE
Missing icons and images

### ISSUE THREAD

**Issue by tofuhead** [lipido/kargos#10]
Kargos doesn't seem to be able to load images correctly. 
in the plugin demo (rotating items) only image I see is the "dialog-ok" icon. 
I see lot of these in item labels: **(href, icon, onclick=href)**, which I think should be replaced with proper variables, and not showing on screen?

[screenshot](http://pasteall.org/pic/show.php?id=114831)

also, I seem to be unable to put any icons on title bar.. it's just text that shows up even if I add **|iconName=dialog-ok**  forexample in the first echoed line.

I'm using Kargos from git. 
this is Kubuntu 17.04

**Comment by lipido** [comment]
I do see them. I am using 16.04. Do you see the "Qt" icons?. Can you send me a screen shot of the dropdown?

Screenshot:
![kargos-demo-shot](https://cloud.githubusercontent.com/assets/1893304/25315063/401d3e9a-284f-11e7-8904-2494b2862255.png)

I assume that you are connected to the net (because Qt and KDE icons are retrieved from the net, imageURL attribute). It is possible that in Kubuntu 17.04 there are no icon named "dialog-cancel"?¿? (only "dialog-ok"?)

**Comment by roachsinai** [comment]
![image](https://user-images.githubusercontent.com/9500049/51798062-393f8f80-2247-11e9-9b92-bf4b1712a5c6.png)

No image for me, too.

**Comment by roachsinai** [comment]
Got this for [unicorn](https://getbitbar.com/plugins/Web/Cornify/cornify.1m.sh)

![image](https://user-images.githubusercontent.com/9500049/51798116-2a0d1180-2248-11e9-9601-6b359d141261.png)
